### ISSUE TITLE
Inter_change_option_place_for graph1

### ISSUE THREAD

**Issue by halaalbahloul** [tiffanalin/dashboardteam5#121]
put option above the graph1 instead of sidebar

**Comment by tiffanalin** [comment]
will remove 'all countries' option and move above graph 1

**Comment by halaalbahloul** [comment]
just cases and deaths option and type
I think it is better to have select countries or continent on sidebar because they are common between all graphs

**Comment by bmarid** [comment]
Agree!

**Comment by tiffanalin** [comment]
yes, thank you for clarifying. will remove 'all countries' (see issue #125 ). And, here will move cases/deaths and type above graph1
