### ISSUE TITLE
Fix_error

### ISSUE THREAD

**Issue by halaalbahloul** [tiffanalin/dashboardteam5#131]
![image](https://user-images.githubusercontent.com/38258858/233338917-5f7c61ef-594c-4fa8-8995-1c0f3d801c8f.png)
have this error while trying to lunch the app!!

**Comment by tiffanalin** [comment]
yes, need to update requirements.txt to run. will we need scipy for the peak detection?

**Comment by tiffanalin** [comment]
ah! it's an old link. let me update

**Comment by tiffanalin** [comment]
updated link, but it's still not working. getting error message: 'ModuleNotFoundError: No module named 'scipy''

**Comment by halaalbahloul** [comment]
can you open issues for update?

**Comment by tiffanalin** [comment]
see issue #136
