### ISSUE TITLE
Requirement: Data file is not stored in the repo and is read on the fly with Pandas.

### ISSUE THREAD

**Issue by tiffanalin** [tiffanalin/dashboardteam5#132]
It looks like our data is now stored in the repo, which is against this requirement. The teacher would like for us to have the most up to date data, so could we revert to what we did previously, reading the url on the fly?

**Comment by bmarid** [comment]
According last updates we can keep document in our repo. I would like to keep two lines: 1) read url, 2) read csv. Like this we can run url for production and use file for development, what do you think?

**Comment by halaalbahloul** [comment]
I think we can speedup the process without storing the file. try to measure that time it takes in the first time
