### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by halaalbahloul** [tiffanalin/dashboardteam5#15]
Deal withh the missing values and Interpolation #

**Comment by halaalbahloul** [comment]
**columns to process:** 
                  'total_deaths','total_cases'
                  'total_deaths_per_million',
                  'total_cases_per_million',

**Comment by tiffanalin** [comment]
agree, those are columns that we need to deal with missing values

**Comment by halaalbahloul** [comment]
grouped by week or month or leave it by days?

**Comment by tiffanalin** [comment]
I think it's ok by days
