### ISSUE TITLE
Recheck normailzation

### ISSUE THREAD

**Issue by halaalbahloul** [tiffanalin/dashboardteam5#24]
#14 #23 

Check line 88
``` df[['total_cases',	'new_cases',	'total_deaths',	'new_deaths',	'total_cases_per_million']]=df[['total_cases',	'new_cases',	'total_deaths',	'new_deaths',	'total_cases_per_million']].apply(lambda x: (x/(df["population"])*1000000),axis=0) ```

I think it should be **df_final**

**Comment by tiffanalin** [comment]
updated in #9. #14 & #23 deleted
