### ISSUE TITLE
Design a user interface

### ISSUE THREAD

**Issue by halaalbahloul** [tiffanalin/dashboardteam5#9]
1. A page title
2. A top-level filter
3. Interactive charts
4. A data table
see: https://blog.streamlit.io/how-to-build-a-real-time-live-dashboard-with-streamlit/#what%E2%80%99s-a-real-time-live-dashboard

**Comment by halaalbahloul** [comment]
you can see also : https://towardsdatascience.com/streamlit-101-an-in-depth-introduction-fc8aad9492f2

**Comment by tiffanalin** [comment]
I made some adjustments to the user interface, let me know what you think

![image](https://user-images.githubusercontent.com/115715961/229528497-2514566b-2886-429c-8baf-a156465a9302.png)
